version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/backend"
    schedule:
      interval: "monthly"
    groups:
      patch-updates:
        update-types:
          - "patch"

  # - package-ecosystem: "npm"
  #   directory: "/frontend"
  #   schedule:
  #     interval: "monthly"
  #   groups:
  #     patch-updates:
  #       update-types:
  #         - "patch"
