services:
  traefik:
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--api.dashboard=true"
    ports:
      - "80:80"
      - "8080:8080"

  postgres:
    ports:
      - "5432:5432"

  backend:
    build:
      target: development
    ports:
      - "8000:8000"
    develop:
      watch:
        - action: sync
          path: ./backend/src
          target: /app/src
          ignore:
            - .venv/

  frontend:
    build:
      target: development
    environment:
      NODE_ENV: development
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: rebuild
          path: ./frontend/package.json
        - action: sync
          path: ./frontend
          target: /app
          ignore:
            - node_modules/
            - .nuxt/
