"""add created_at to wishlists

Revision ID: 6aebf7eb6ed4
Revises: 0c93fe630cd1
Create Date: 2024-07-06 21:52:43.191693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6aebf7eb6ed4'
down_revision: Union[str, None] = '0c93fe630cd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishlists', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wishlists', 'created_at')
    # ### end Alembic commands ###
