"""initial

Revision ID: d639cd7c411e
Revises:
Create Date: 2026-09-22 11:00:07.110546

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d639cd7c411e"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("password_hash", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("is_superuser", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("username"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "wishlists",
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("owner_username", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("is_archived", sa.Boolean(), nullable=True),
        sa.Column("is_public", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_username"], ["users.username"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_table(
        "wishlist_items",
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column("wishlist_uuid", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=True),
        sa.Column(
            "measurement_unit",
            sa.Enum("PIECE", "METER", "KILOGRAM", name="measurementunit"),
            nullable=True,
        ),
        sa.Column(
            "priority", sa.Enum("LOW", "MEDIUM", "HIGH", name="priority"), nullable=True
        ),
        sa.Column("is_purchased", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["wishlist_uuid"], ["wishlists.uuid"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("wishlist_items")
    op.drop_table("wishlists")
    op.drop_table("users")
    # ### end Alembic commands ###
